### ISSUE TITLE
Environment for compiling binary files

### ISSUE THREAD

**Issue by ghost** [lancethepants/shadowsocks-libev-mipsel-static#1]
Hi，which docker environment does this script need to run under?

**Comment by lancethepants** [comment]
This I compiled using a toolchain from my project Tomatoware.
https://github.com/lancethepants/tomatoware

I haven't compiled this for quite some time though.

**Comment by ghost** [comment]
What do I need to do to configure it correctly? I downloaded mipsel-soft-mmc.tgz first,
Then unzip it to /mmc, specify the path, export PATH=/mmc/bin:$PATH. Is this correct? Can you provide the complete steps for compiling shadowsocks-libev-mipsel-static? thank you

**Comment by lancethepants** [comment]
I've uploaded a new toolchain for mipsel, so get the latest version.
https://files.lancethepants.com/Toolchains/mipsel/
To install it:
```sudo mkdir /opt/tomatoware```
```sudo chmod 777 /opt/tomatoware```
```tar zxvf mipsel-soft-mmc.tgz -C /opt/tomatoware```
Then add ```/opt/tomatoware/mipsel-soft-mmc/bin``` to you PATH.
Then clone this repo, I've just updated all the packages to their latest versions.
Then go into folder and run ```./shadowsocks-libev.sh```
Final binaries can be found in ~/shadowsocks-libev/shadowsocks-libev/opt/bin

**Comment by lancethepants** [comment]
I've also uploaded the latest version as well.
https://files.lancethepants.com/Binaries/shadowsocks-libev/mipsel/

**Comment by lancethepants** [comment]
Did you get it work?

**Comment by ghost** [comment]
In fact, I use this device   Redmi AC2100 4X4 MUMO
http://en.techinfodepot.shoutwiki.com/wiki/Xiaomi_Redmi_AC2100_(RM2100)
The device has not yet been transplanted by the author to make tomato firmware. I understand that the mipsel architecture can be used for mipsel Merlin firmware,
 https://github.com/ferhung-mtk/asuswrt_RM2100

Unfortunately, it failed.

**Comment by ghost** [comment]
thank you all the same.

**Comment by lancethepants** [comment]
That router had a qualcomm cpu, so it will never be supported Merlin of Tomato. I compile a static binary, so it should be able to work still on a mipsel router if you're able to side load binaries.

**Comment by ghost** [comment]
Yes, you are right. Put it in a "padavan firmware" and it works. Thank you very much.
